title: "Ditiro Rampate"
email: "ditirorampate@gmail.com"
description: >-
  Computer Systems Engineer building practical software, data, and machine learning solutions.
baseurl: "/"
url: "https://ditirodt.github.io"
twitter_username: "ditiro_dt"
github_username: "ditirodt"
linkedin_username: "ditiro-rampate"

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
